<?php


namespace App\Support\Discount\Validator;


use App\Models\Shop\Coupon;
use App\Support\Discount\Validator\contracts\AbstractCouponValidator;
use App\Support\Discount\Validator\Exceptions\CouponHasExpiredException;

class IsExpired extends AbstractCouponValidator
{
    public function validate(Coupon $coupon)
    {
        if ($coupon->isExpired()) {
            throw new CouponHasExpiredException();
        }
        return parent::validate($coupon); // TODO: Change the autogenerated stub
    }
}
